from toontown.toonbase import TTLocalizer

SuitAttributes =  {'f': {'name': TTLocalizer.SuitFlunky,
       'singularname': TTLocalizer.SuitFlunkyS,
       'pluralname': TTLocalizer.SuitFlunkyP,
       'track': 'boss',
       'level': 0,
       'levelMod': 7,
       'attacks': (('PoundKey', 2, 75, 30, 1, 1, 5, 0), 
                     ('Shred', 3, 50, 30, 1, 1, 5, 0), 
                     ('ClipOnTie', 1, 75, 60, 0.5, 1, 5, 0))},

 'p': {'name': TTLocalizer.SuitPencilPusher,
       'singularname': TTLocalizer.SuitPencilPusherS,
       'pluralname': TTLocalizer.SuitPencilPusherP,
       'track': 'boss',
       'level': 1,
       'levelMod': 6,
       'attacks': (('FountainPen', 2, 75, 20, 1.75, 5, 0),
                   ('RubOut', 4, 75, 20, 2, 5, 0),
                   ('FingerWag', 1, 75, 35, 0.75, 5, 0),
                   ('WriteOff', 4, 75, 5, 2, 5, 0),
                   ('FillWithLead', 3, 75, 20, 1, 5, 0))},
                   
 'ym': {'name': TTLocalizer.SuitYesman,
        'singularname': TTLocalizer.SuitYesmanS,
        'pluralname': TTLocalizer.SuitYesmanP,
        'track': 'boss',
        'level': 2,
        'levelMod': 5,
        'attacks': (('RubberStamp', 2, 50, 35, 0.5, 5, 0),
                    ('RazzleDazzle', 1, 50, 25, 0, 5, 0),
                    ('Synergy', 4, 50, 5, 1, 5, 0),
                    ('TeeOff', 3, 50, 35, 0.5, 5, 0))},

 'mm': {'name': TTLocalizer.SuitMicromanager,
        'singularname': TTLocalizer.SuitMicromanagerS,
        'pluralname': TTLocalizer.SuitMicromanagerP,
        'track': 'boss',
        'level': 3,
        'levelMod': 5,
        'attacks': (('Demotion', 6, 50, 30, 3, 5, 0),
                    ('FingerWag', 4, 50, 10, 2, 5, 0),
                    ('FountainPen', 3, 50, 15, 1.75, 5, 0),
                    ('BrainStorm', 4, 5, 25, 2.75, 5, 0),
                    ('BuzzWord', 4, 50, 20, 2.75, 5, 0))},

 'ds': {'name': TTLocalizer.SuitDownsizer,
        'singularname': TTLocalizer.SuitDownsizerS,
        'pluralname': TTLocalizer.SuitDownsizerP,
        'track': 'boss',
        'level': 4,
        'levelMod': 5,
        'attacks': (('Canned', 5, 60, 25, 1.75, 5, 0),
                    ('Downsize', 8, 50, 35, 1.75, 5, 0),
                    ('PinkSlip', 4, 60, 25, 1, 5, 0),
                    ('Sacked', 5, 50, 15, 1, 5, 0))},

 'hh': {'name': TTLocalizer.SuitHeadHunter,
        'singularname': TTLocalizer.SuitHeadHunterS,
        'pluralname': TTLocalizer.SuitHeadHunterP,
        'track': 'boss',
        'level': 5,
        'levelMod': 4,
        'attacks': (('FountainPen', 5, 60, 15, 1.75, 5, 0),
                    ('GlowerPower', 7, 50, 20, 1.5, 5, 0),
                    ('HalfWindsor', 8, 60, 20, 2, 5, 0),
                    ('HeadShrink', 10, 65, 35, 2.75, 5, 0),
                    ('Rolodex', 6, 60, 10, 1, 5, 0))},

 'cr': {'name': TTLocalizer.SuitCorporateRaider,
        'singularname': TTLocalizer.SuitCorporateRaiderS,
        'pluralname': TTLocalizer.SuitCorporateRaiderP,
        'track': 'boss',
        'level': 6,
        'levelMod': 4,
        'attacks': (('Canned', 6, 60, 20, 1, 5, 0),
                    ('EvilEye', 12, 60, 35, 3, 5, 0),
                    ('PlayHardball', 7, 60, 30, 2.25, 5, 0),
                    ('PowerTie', 10, 65, 15, 2, 5, 0))},

 'tbc': {'name': TTLocalizer.SuitTheBigCheese,
         'singularname': TTLocalizer.SuitTheBigCheeseS,
         'pluralname': TTLocalizer.SuitTheBigCheeseP,
         'track': 'boss',
         'level': 7,
         'levelMod': 4,
         'attacks': (('CigarSmoke', 10, 55, 20, 2.5, 5, 0),
                     ('FloodTheMarket', 14, 70, 10, 2, 5, 0),
                     ('SongAndDance', 14, 60, 20, 1.5, 5, 0),
                     ('TeeOff', 8, 55, 50, 3, 5, 0))},


                     

 'cc': {'name': TTLocalizer.SuitColdCaller,
        'singularname': TTLocalizer.SuitColdCallerS,
        'pluralname': TTLocalizer.SuitColdCallerP,
        'track': 'sales',
        'level': 0,
        'levelMod': 7,
        'attacks': (('FreezeAssets', 1, 90, 5, 0, 5, 0),
                    ('PoundKey', 2, 75, 25, 0.75, 5, 0),
                    ('DoubleTalk', 2, 50, 25, 1.5, 5, 0),
                    ('HotAir', 3, 50, 45, 1.75, 5, 0))},

 'tm': {'name': TTLocalizer.SuitTelemarketer,
        'singularname': TTLocalizer.SuitTelemarketerS,
        'pluralname': TTLocalizer.SuitTelemarketerP,
        'track': 'sales',
        'level': 1,
        'levelMod': 6,
        'attacks': (('ClipOnTie', 2, 75, 15, 0.5, 5, 0),
                    ('PickPocket', 1, 75, 15, 0, 5, 0),
                    ('Rolodex', 4, 50, 30, 2, 5, 0),
                    ('DoubleTalk', 4, 75, 40, 2, 5, 0))},

 'nd': {'name': TTLocalizer.SuitNameDropper,
        'singularname': TTLocalizer.SuitNameDropperS,
        'pluralname': TTLocalizer.SuitNameDropperP,
        'track': 'sales',
        'level': 2,
        'levelMod': 5,
        'attacks': (('RazzleDazzle', 4, 75, 30, 2, 5, 0),
                    ('Rolodex', 5, 95, 40, 2.25, 5, 0),
                    ('Synergy', 3, 50, 15, 2.25, 5, 0),
                    ('PickPocket', 2, 95, 15, 2, 5, 0))},

 'gh': {'name': TTLocalizer.SuitGladHander,
        'singularname': TTLocalizer.SuitGladHanderS,
        'pluralname': TTLocalizer.SuitGladHanderP,
        'track': 'sales',
        'level': 3,
        'levelMod': 5,
        'attacks': (('RubberStamp', 4, 90, 40, 0.75, 5, 0),
                    ('FountainPen', 3, 70, 40, 0.5, 5, 0),
                    ('Filibuster', 4, 30, 10, 2.75, 5, 0),
                    ('Schmooze', 5, 55, 10, 3.75, 5, 0))},

 'ms': {'name': TTLocalizer.SuitMoverShaker,
        'singularname': TTLocalizer.SuitMoverShakerS,
        'pluralname': TTLocalizer.SuitMoverShakerP,
        'track': 'sales',
        'level': 4,
        'levelMod': 5,
        'attacks': (('BrainStorm', 5, 60, 15, 1.75, 5, 0),
                    ('HalfWindsor', 6, 50, 20, 2.5, 5, 0),
                    ('Quake', 9, 60, 20, 3, 5, 0),
                    ('Shake', 6, 70, 25, 2, 5, 0),
                    ('Tremor', 5, 50, 20, 1, 5, 0))},

 'tf': {'name': TTLocalizer.SuitTwoFace,
        'singularname': TTLocalizer.SuitTwoFaceS,
        'pluralname': TTLocalizer.SuitTwoFaceP,
        'track': 'sales',
        'level': 5,
        'levelMod': 4,
        'attacks': (('EvilEye', 10, 60, 30, 2, 5, 0),
                    ('HangUp', 7, 50, 15, 1.5, 5, 0),
                    ('RazzleDazzle', 8, 60, 30, 2, 5, 0),
                    ('RedTape', 6, 60, 25, 1, 5, 0))},

 'm': {'name': TTLocalizer.SuitTheMingler,
       'singularname': TTLocalizer.SuitTheMinglerS,
       'pluralname': TTLocalizer.SuitTheMinglerP,
       'track': 'sales',
       'level': 6,
       'levelMod': 4,
       'attacks': (('BuzzWord', 10, 60, 20, 1, 5, 0),
                   ('ParadigmShift', 12, 60, 25, 3, 5, 0),
                   ('PowerTrip', 10, 60, 15, 2, 5, 0),
                   ('Schmooze', 7, 55, 30, 2.25, 5, 0),
                   ('TeeOff', 8, 70, 10, 1, 5, 0))},

 'mh': {'name': TTLocalizer.SuitMrHollywood,
        'singularname': TTLocalizer.SuitMrHollywoodS,
        'pluralname': TTLocalizer.SuitMrHollywoodP,
        'track': 'sales',
        'level': 7,
        'levelMod': 4,
        'attacks': (('PowerTrip', 10, 55, 50, 2.5, 5, 0), 
                    ('RazzleDazzle', 8, 70, 50, 3, 5, 0))},




 'sc': {'name': TTLocalizer.SuitShortChange,
        'singularname': TTLocalizer.SuitShortChangeS,
        'pluralname': TTLocalizer.SuitShortChangeP,
        'track': 'cash',
        'level': 0,
        'levelMod': 7,
        'attacks': (('Watercooler', 2, 50, 20, 1, 5, 0),
                    ('BounceCheck', 3, 75, 15, 2, 5, 0),
                    ('ClipOnTie', 1, 50, 25, 0.5, 5, 0),
                    ('PickPocket', 2, 95, 40, 1, 5, 0))},

 'pp': {'name': TTLocalizer.SuitPennyPincher,
        'singularname': TTLocalizer.SuitPennyPincherS,
        'pluralname': TTLocalizer.SuitPennyPincherP,
        'track': 'cash',
        'level': 1,
        'levelMod': 6,
        'attacks': (('BounceCheck', 4, 75, 45, 2, 5, 0), 
                    ('FreezeAssets', 2, 75, 20, 1.75, 5, 0), 
                    ('FingerWag', 1, 50, 35, 1.25, 5, 0))},

 'tw': {'name': TTLocalizer.SuitTightwad,
        'singularname': TTLocalizer.SuitTightwadS,
        'pluralname': TTLocalizer.SuitTightwadP,
        'track': 'cash',
        'level': 2,
        'levelMod': 5,
        'attacks': (('Fired', 3, 75, 75, 0.75, 5, 0),
                    ('GlowerPower', 3, 95, 10, 2.25, 5, 0),
                    ('FingerWag', 3, 75, 5, 0.5, 5, 0),
                    ('FreezeAssets', 3, 75, 5, 2.25, 5, 0),
                    ('BounceCheck', 5, 75, 5, 3.25, 5, 0))},

 'bc': {'name': TTLocalizer.SuitBeanCounter,
        'singularname': TTLocalizer.SuitBeanCounterS,
        'pluralname': TTLocalizer.SuitBeanCounterP,
        'track': 'cash',
        'level': 3,
        'levelMod': 5,
        'attacks': (('Audit', 4, 95, 20, 2.75, 5, 0),
                    ('Calculate', 4, 75, 25, 2.75, 5, 0),
                    ('Tabulate', 4, 75, 25, 2.75, 5, 0),
                    ('WriteOff', 4, 95, 30, 2.75, 5, 0))},

 'nc': {'name': TTLocalizer.SuitNumberCruncher,
        'singularname': TTLocalizer.SuitNumberCruncherS,
        'pluralname': TTLocalizer.SuitNumberCruncherP,
        'track': 'cash',
        'level': 4,
        'levelMod': 5,
        'attacks': (('Audit', 5, 60, 15, 1.75, 5, 0),
                    ('Calculate', 6, 50, 30, 1.75, 5, 0),
                    ('Crunch', 8, 60, 35, 1.75, 5, 0),
                    ('Tabulate', 5, 50, 20, 1, 5, 0))},
                    
 'mb': {'name': TTLocalizer.SuitMoneyBags,
        'singularname': TTLocalizer.SuitMoneyBagsS,
        'pluralname': TTLocalizer.SuitMoneyBagsP,
        'track': 'cash',
        'level': 5,
        'levelMod': 4,
        'attacks': (('Liquidate', 10, 60, 30, 2, 5, 0), 
                      ('MarketCrash', 8, 60, 45, 2, 5, 0), 
                      ('PowerTie', 6, 60, 25, 1, 5, 0))},

 'ls': {'name': TTLocalizer.SuitLoanShark,
        'singularname': TTLocalizer.SuitLoanSharkS,
        'pluralname': TTLocalizer.SuitLoanSharkP,
        'track': 'cash',
        'level': 6,
        'levelMod': 4,
        'attacks': (('Bite', 10, 60, 30, 1.5, 5, 0),
                    ('Chomp', 12, 60, 35, 3, 5, 0),
                    ('PlayHardball', 9, 55, 20, 1.5, 5, 0),
                    ('WriteOff', 6, 70, 15, 2, 5, 0))},

 'rb': {'name': TTLocalizer.SuitRobberBaron,
        'singularname': TTLocalizer.SuitRobberBaronS,
        'pluralname': TTLocalizer.SuitRobberBaronP,
        'track': 'cash',
        'level': 7,
        'levelMod': 4,
        'attacks': (('PowerTrip', 11, 60, 50, 2.5, 5, 0), 
                      ('TeeOff', 10, 60, 50, 2, 5, 0))},




 'bf': {'name': TTLocalizer.SuitBottomFeeder,
        'singularname': TTLocalizer.SuitBottomFeederS,
        'pluralname': TTLocalizer.SuitBottomFeederP,
        'track': 'law',
        'level': 0,
        'levelMod': 7,
        'attacks': (('RubberStamp', 2, 75, 20, 1, 5, 0),
                    ('Shred', 2, 50, 20, 2, 5, 0),
                    ('Watercooler', 3, 95, 10, 1, 5, 0),
                    ('PickPocket', 1, 25, 50, 0.5, 5, 0))},

 'b': {'name': TTLocalizer.SuitBloodsucker,
       'singularname': TTLocalizer.SuitBloodsuckerS,
       'pluralname': TTLocalizer.SuitBloodsuckerP,
       'track': 'law',
       'level': 1,
       'levelMod': 6,
       'attacks': (('EvictionNotice', 1, 75, 20, 0.75, 5, 0),
                   ('RedTape', 2, 75, 20, 1.75, 5, 0),
                   ('Withdrawal', 6, 95, 10, 2, 5, 0),
                   ('Liquidate', 2, 50, 50, 1.75, 5, 0))},

 'dt': {'name': TTLocalizer.SuitDoubleTalker,
        'singularname': TTLocalizer.SuitDoubleTalkerS,
        'pluralname': TTLocalizer.SuitDoubleTalkerP,
        'track': 'law',
        'level': 2,
        'levelMod': 5,
        'attacks': (('RubberStamp', 1, 50, 5, 0, 5, 0),
                    ('BounceCheck', 1, 50, 5, 0, 5, 0),
                    ('BuzzWord', 1, 50, 20, 1.25, 5, 0),
                    ('DoubleTalk', 6, 50, 25, 3, 5, 0),
                    ('Jargon', 3, 50, 25, 2.25, 5, 0),
                    ('MumboJumbo', 3, 50, 20, 2.25, 5, 0))},

 'ac': {'name': TTLocalizer.SuitAmbulanceChaser,
        'singularname': TTLocalizer.SuitAmbulanceChaserS,
        'pluralname': TTLocalizer.SuitAmbulanceChaserP,
        'track': 'law',
        'level': 3,
        'levelMod': 5,
        'attacks': (('Shake', 4, 75, 15, 2.75, 5, 0),
                    ('RedTape', 6, 75, 30, 3.25, 5, 0),
                    ('Rolodex', 3, 75, 20, 1, 5, 0),
                    ('HangUp', 2, 75, 35, 1, 5, 0))},

 'bs': {'name': TTLocalizer.SuitBackStabber,
        'singularname': TTLocalizer.SuitBackStabberS,
        'pluralname': TTLocalizer.SuitBackStabberP,
        'track': 'law',
        'level': 4,
        'levelMod': 5,
        'attacks': (('GuiltTrip', 8, 60, 40, 2.5, 5, 0), 
                    ('RestrainingOrder', 6, 50, 25, 1.75, 5, 0), 
                    ('FingerWag', 5, 50, 35, 1, 5, 0))},

 'sd': {'name': TTLocalizer.SuitSpinDoctor,
        'singularname': TTLocalizer.SuitSpinDoctorS,
        'pluralname': TTLocalizer.SuitSpinDoctorP,
        'track': 'law',
        'level': 5,
        'levelMod': 5,
        'attacks': (('ParadigmShift', 9, 60, 30, 2, 5, 0),
                    ('Quake', 8, 60, 20, 2, 5, 0),
                    ('Spin', 10, 70, 35, 2.5, 5, 0),
                    ('WriteOff', 6, 60, 15, 1, 5, 0))},

 'le': {'name': TTLocalizer.SuitLegalEagle,
        'singularname': TTLocalizer.SuitLegalEagleS,
        'pluralname': TTLocalizer.SuitLegalEagleP,
        'track': 'law',
        'level': 6,
        'levelMod': 4,
        'attacks': (('EvilEye', 10, 60, 20, 1.5, 5, 0),
                    ('Jargon', 7, 60, 15, 2, 5, 0),
                    ('Legalese', 11, 55, 35, 2.5, 5, 0),
                    ('PeckingOrder', 12, 70, 30, 2.5, 5, 0))},

 'bw': {'name': TTLocalizer.SuitBigWig,
        'singularname': TTLocalizer.SuitBigWigS,
        'pluralname': TTLocalizer.SuitBigWigP,
        'track': 'law',
        'level': 7,
        'levelMod': 4,
        'attacks': (('PowerTrip', 10, 75, 50, 1.5, 5, 0), 
                    ('ThrowBook', 13, 80, 50, 2, 5, 0))}} 